/*
   Go Language Raspberry Pi Interface
   (c) Copyright David Thorpe 2016-2018
   All Rights Reserved
   Documentation http://djthorpe.github.io/gopi/
   For Licensing and Usage information, please see LICENSE.md
*/

package remotes

import (
	"github.com/djthorpe/gopi"
)

/////////////////////////////////////////////////////////////////////
// CONSTANTS

const (
	KEYCODE_MIN RemoteCode = iota + RemoteCode(gopi.KEYCODE_MAX)
	KEYCODE_EJECT
	KEYCODE_POWER_OFF
	KEYCODE_POWER_ON
	KEYCODE_POWER_TOGGLE
	KEYCODE_INPUT_SELECT
	KEYCODE_INPUT_PC
	KEYCODE_INPUT_VIDEO1
	KEYCODE_INPUT_VIDEO2
	KEYCODE_INPUT_VIDEO3
	KEYCODE_INPUT_VIDEO4
	KEYCODE_INPUT_VIDEO5
	KEYCODE_INPUT_HDMI1
	KEYCODE_INPUT_HDMI2
	KEYCODE_INPUT_HDMI3
	KEYCODE_INPUT_HDMI4
	KEYCODE_INPUT_HDMI5
	KEYCODE_INPUT_AUX1
	KEYCODE_INPUT_AUX2
	KEYCODE_INPUT_AUX3
	KEYCODE_INPUT_AUX4
	KEYCODE_INPUT_AUX5
	KEYCODE_INPUT_CD
	KEYCODE_INPUT_DVD
	KEYCODE_INPUT_PHONO
	KEYCODE_INPUT_TAPE1
	KEYCODE_INPUT_TAPE2
	KEYCODE_INPUT_TUNER
	KEYCODE_INPUT_ANALOG
	KEYCODE_INPUT_DIGITAL
	KEYCODE_INPUT_INTERNET
	KEYCODE_INPUT_TEXT
	KEYCODE_INPUT_NEXT
	KEYCODE_INPUT_PREV
	KEYCODE_VIDEO_ASPECT
	KEYCODE_VIDEO_PIP
	KEYCODE_AUDIO_MONITOR
	KEYCODE_KEYPAD_1
	KEYCODE_KEYPAD_2
	KEYCODE_KEYPAD_3
	KEYCODE_KEYPAD_4
	KEYCODE_KEYPAD_5
	KEYCODE_KEYPAD_6
	KEYCODE_KEYPAD_7
	KEYCODE_KEYPAD_8
	KEYCODE_KEYPAD_9
	KEYCODE_KEYPAD_0
	KEYCODE_KEYPAD_SELECT
	KEYCODE_CLEAR
	KEYCODE_TIMER
	KEYCODE_VOLUME_UP
	KEYCODE_VOLUME_DOWN
	KEYCODE_VOLUME_MUTE
	KEYCODE_CHANNEL_UP
	KEYCODE_CHANNEL_DOWN
	KEYCODE_CHANNEL_PREV
	KEYCODE_CHANNEL_GUIDE
	KEYCODE_RECORD
	KEYCODE_RECORD_SPEED
	KEYCODE_PLAY_SPEED
	KEYCODE_DISPLAY
	KEYCODE_MENU
	KEYCODE_INFO
	KEYCODE_THUMBS_UP
	KEYCODE_THUMBS_DOWN
	KEYCODE_FAVOURITE
	KEYCODE_BUTTON_RED
	KEYCODE_BUTTON_GREEN
	KEYCODE_BUTTON_YELLOW
	KEYCODE_BUTTON_BLUE
	KEYCODE_SEARCH_LEFT
	KEYCODE_SEARCH_RIGHT
	KEYCODE_CHAPTER_NEXT
	KEYCODE_CHAPTER_PREV
	KEYCODE_NAV_UP
	KEYCODE_NAV_DOWN
	KEYCODE_NAV_LEFT
	KEYCODE_NAV_RIGHT
	KEYCODE_NAV_SELECT
	KEYCODE_NAV_BACK
	KEYCODE_SUBTITLE_TOGGLE
	KEYCODE_SUBTITLE_ON
	KEYCODE_SUBTITLE_OFF
	KEYCODE_MAX
)

/////////////////////////////////////////////////////////////////////
// STRINGIFY

func (k RemoteCode) String() string {
	switch k {
	case KEYCODE_EJECT:
		return "KEYCODE_EJECT"
	case KEYCODE_POWER_OFF:
		return "KEYCODE_POWER_OFF"
	case KEYCODE_POWER_ON:
		return "KEYCODE_POWER_ON"
	case KEYCODE_POWER_TOGGLE:
		return "KEYCODE_POWER_TOGGLE"
	case KEYCODE_INPUT_SELECT:
		return "KEYCODE_INPUT_SELECT"
	case KEYCODE_INPUT_PC:
		return "KEYCODE_INPUT_PC"
	case KEYCODE_INPUT_VIDEO1:
		return "KEYCODE_INPUT_VIDEO1"
	case KEYCODE_INPUT_VIDEO2:
		return "KEYCODE_INPUT_VIDEO2"
	case KEYCODE_INPUT_VIDEO3:
		return "KEYCODE_INPUT_VIDEO3"
	case KEYCODE_INPUT_VIDEO4:
		return "KEYCODE_INPUT_VIDEO4"
	case KEYCODE_INPUT_VIDEO5:
		return "KEYCODE_INPUT_VIDEO5"
	case KEYCODE_INPUT_HDMI1:
		return "KEYCODE_INPUT_HDMI1"
	case KEYCODE_INPUT_HDMI2:
		return "KEYCODE_INPUT_HDMI2"
	case KEYCODE_INPUT_HDMI3:
		return "KEYCODE_INPUT_HDMI3"
	case KEYCODE_INPUT_HDMI4:
		return "KEYCODE_INPUT_HDMI4"
	case KEYCODE_INPUT_HDMI5:
		return "KEYCODE_INPUT_HDMI5"
	case KEYCODE_INPUT_AUX1:
		return "KEYCODE_INPUT_AUX1"
	case KEYCODE_INPUT_AUX2:
		return "KEYCODE_INPUT_AUX2"
	case KEYCODE_INPUT_AUX3:
		return "KEYCODE_INPUT_AUX3"
	case KEYCODE_INPUT_AUX4:
		return "KEYCODE_INPUT_AUX4"
	case KEYCODE_INPUT_AUX5:
		return "KEYCODE_INPUT_AUX5"
	case KEYCODE_INPUT_CD:
		return "KEYCODE_INPUT_CD"
	case KEYCODE_INPUT_DVD:
		return "KEYCODE_INPUT_DVD"
	case KEYCODE_INPUT_PHONO:
		return "KEYCODE_INPUT_PHONO"
	case KEYCODE_INPUT_TAPE1:
		return "KEYCODE_INPUT_TAPE1"
	case KEYCODE_INPUT_TAPE2:
		return "KEYCODE_INPUT_TAPE2"
	case KEYCODE_INPUT_TUNER:
		return "KEYCODE_INPUT_TUNER"
	case KEYCODE_INPUT_ANALOG:
		return "KEYCODE_INPUT_ANALOG"
	case KEYCODE_INPUT_DIGITAL:
		return "KEYCODE_INPUT_DIGITAL"
	case KEYCODE_INPUT_INTERNET:
		return "KEYCODE_INPUT_INTERNET"
	case KEYCODE_INPUT_TEXT:
		return "KEYCODE_INPUT_TEXT"
	case KEYCODE_INPUT_NEXT:
		return "KEYCODE_INPUT_NEXT"
	case KEYCODE_INPUT_PREV:
		return "KEYCODE_INPUT_PREV"
	case KEYCODE_VIDEO_ASPECT:
		return "KEYCODE_VIDEO_ASPECT"
	case KEYCODE_VIDEO_PIP:
		return "KEYCODE_VIDEO_PIP"
	case KEYCODE_AUDIO_MONITOR:
		return "KEYCODE_AUDIO_MONITOR"
	case KEYCODE_KEYPAD_1:
		return "KEYCODE_KEYPAD_1"
	case KEYCODE_KEYPAD_2:
		return "KEYCODE_KEYPAD_2"
	case KEYCODE_KEYPAD_3:
		return "KEYCODE_KEYPAD_3"
	case KEYCODE_KEYPAD_4:
		return "KEYCODE_KEYPAD_4"
	case KEYCODE_KEYPAD_5:
		return "KEYCODE_KEYPAD_5"
	case KEYCODE_KEYPAD_6:
		return "KEYCODE_KEYPAD_6"
	case KEYCODE_KEYPAD_7:
		return "KEYCODE_KEYPAD_7"
	case KEYCODE_KEYPAD_8:
		return "KEYCODE_KEYPAD_8"
	case KEYCODE_KEYPAD_9:
		return "KEYCODE_KEYPAD_9"
	case KEYCODE_KEYPAD_0:
		return "KEYCODE_KEYPAD_0"
	case KEYCODE_KEYPAD_SELECT:
		return "KEYCODE_KEYPAD_SELECT"
	case KEYCODE_CLEAR:
		return "KEYCODE_CLEAR"
	case KEYCODE_TIMER:
		return "KEYCODE_TIMER"
	case KEYCODE_VOLUME_UP:
		return "KEYCODE_VOLUME_UP"
	case KEYCODE_VOLUME_DOWN:
		return "KEYCODE_VOLUME_DOWN"
	case KEYCODE_VOLUME_MUTE:
		return "KEYCODE_VOLUME_MUTE"
	case KEYCODE_CHANNEL_UP:
		return "KEYCODE_CHANNEL_UP"
	case KEYCODE_CHANNEL_DOWN:
		return "KEYCODE_CHANNEL_DOWN"
	case KEYCODE_CHANNEL_PREV:
		return "KEYCODE_CHANNEL_PREV"
	case KEYCODE_CHANNEL_GUIDE:
		return "KEYCODE_CHANNEL_GUIDE"
	case KEYCODE_RECORD:
		return "KEYCODE_RECORD"
	case KEYCODE_RECORD_SPEED:
		return "KEYCODE_RECORD_SPEED"
	case KEYCODE_PLAY_SPEED:
		return "KEYCODE_PLAY_SPEED"
	case KEYCODE_DISPLAY:
		return "KEYCODE_DISPLAY"
	case KEYCODE_MENU:
		return "KEYCODE_MENU"
	case KEYCODE_INFO:
		return "KEYCODE_INFO"
	case KEYCODE_THUMBS_UP:
		return "KEYCODE_THUMBS_UP"
	case KEYCODE_THUMBS_DOWN:
		return "KEYCODE_THUMBS_DOWN"
	case KEYCODE_FAVOURITE:
		return "KEYCODE_FAVOURITE"
	case KEYCODE_BUTTON_RED:
		return "KEYCODE_BUTTON_RED"
	case KEYCODE_BUTTON_GREEN:
		return "KEYCODE_BUTTON_GREEN"
	case KEYCODE_BUTTON_YELLOW:
		return "KEYCODE_BUTTON_YELLOW"
	case KEYCODE_BUTTON_BLUE:
		return "KEYCODE_BUTTON_BLUE"
	case KEYCODE_SEARCH_LEFT:
		return "KEYCODE_SEARCH_LEFT"
	case KEYCODE_SEARCH_RIGHT:
		return "KEYCODE_SEARCH_RIGHT"
	case KEYCODE_CHAPTER_NEXT:
		return "KEYCODE_CHAPTER_NEXT"
	case KEYCODE_CHAPTER_PREV:
		return "KEYCODE_CHAPTER_PREV"
	case KEYCODE_NAV_UP:
		return "KEYCODE_NAV_UP"
	case KEYCODE_NAV_DOWN:
		return "KEYCODE_NAV_DOWN"
	case KEYCODE_NAV_LEFT:
		return "KEYCODE_NAV_LEFT"
	case KEYCODE_NAV_RIGHT:
		return "KEYCODE_NAV_RIGHT"
	case KEYCODE_NAV_SELECT:
		return "KEYCODE_NAV_SELECT"
	case KEYCODE_NAV_BACK:
		return "KEYCODE_NAV_BACK"
	case KEYCODE_SUBTITLE_TOGGLE:
		return "KEYCODE_SUBTITLE_TOGGLE"
	case KEYCODE_SUBTITLE_ON:
		return "KEYCODE_SUBTITLE_ON"
	case KEYCODE_SUBTITLE_OFF:
		return "KEYCODE_SUBTITLE_OFF"
	default:
		return "[?? Invalid RemoteCode]"
	}
}
