/*
   Go Language Raspberry Pi Interface
   (c) Copyright David Thorpe 2016-2018
   All Rights Reserved
   Documentation http://djthorpe.github.io/gopi/
   For Licensing and Usage information, please see LICENSE.md
*/

package remotes

import (
	"github.com/djthorpe/gopi"
)

const (
	KEYCODE_EJECT gopi.KeyCode = iota
	KEYCODE_POWER_TOGGLE
	KEYCODE_INPUT_SELECT
	KEYCODE_AUDIO_MONITOR
	KEYCODE_CLEAR
	KEYCODE_KEYPAD_1
	KEYCODE_KEYPAD_2
	KEYCODE_KEYPAD_3
	KEYCODE_KEYPAD_4
	KEYCODE_KEYPAD_5
	KEYCODE_KEYPAD_6
	KEYCODE_KEYPAD_7
	KEYCODE_KEYPAD_8
	KEYCODE_KEYPAD_9
	KEYCODE_KEYPAD_0
	KEYCODE_KEYPAD_SELECT
	KEYCODE_TIMER
	KEYCODE_VOLUME_UP
	KEYCODE_VOLUME_DOWN
	KEYCODE_CHANNEL_UP
	KEYCODE_CHANNEL_DOWN
	KEYCODE_RECORD
	KEYCODE_RECORD_SPEED
	KEYCODE_PLAY_SPEED
	KEYCODE_DISPLAY
	KEYCODE_SEARCH_LEFT
	KEYCODE_SEARCH_RIGHT
	KEYCODE_MENU
	KEYCODE_NAVIGATION_UP
	KEYCODE_NAVIGATION_DOWN
	KEYCODE_NAVIGATION_LEFT
	KEYCODE_NAVIGATION_RIGHT
	KEYCODE_NAVIGATION_SELECT
)
