// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remotes/remotes.proto

/*
Package remotes is a generated protocol buffer package.

It is generated from these files:
	remotes/remotes.proto

It has these top-level messages:
	EmptyRequest
	EmptyReply
	Point
	InputEvent
*/
package remotes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/duration"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InputDeviceType int32

const (
	InputDeviceType_INPUT_TYPE_NONE        InputDeviceType = 0
	InputDeviceType_INPUT_TYPE_KEYBOARD    InputDeviceType = 1
	InputDeviceType_INPUT_TYPE_MOUSE       InputDeviceType = 2
	InputDeviceType_INPUT_TYPE_TOUCHSCREEN InputDeviceType = 4
	InputDeviceType_INPUT_TYPE_JOYSTICK    InputDeviceType = 8
	InputDeviceType_INPUT_TYPE_REMOTE      InputDeviceType = 16
)

var InputDeviceType_name = map[int32]string{
	0:  "INPUT_TYPE_NONE",
	1:  "INPUT_TYPE_KEYBOARD",
	2:  "INPUT_TYPE_MOUSE",
	4:  "INPUT_TYPE_TOUCHSCREEN",
	8:  "INPUT_TYPE_JOYSTICK",
	16: "INPUT_TYPE_REMOTE",
}
var InputDeviceType_value = map[string]int32{
	"INPUT_TYPE_NONE":        0,
	"INPUT_TYPE_KEYBOARD":    1,
	"INPUT_TYPE_MOUSE":       2,
	"INPUT_TYPE_TOUCHSCREEN": 4,
	"INPUT_TYPE_JOYSTICK":    8,
	"INPUT_TYPE_REMOTE":      16,
}

func (x InputDeviceType) String() string {
	return proto.EnumName(InputDeviceType_name, int32(x))
}
func (InputDeviceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InputEventType int32

const (
	InputEventType_INPUT_EVENT_NONE          InputEventType = 0
	InputEventType_INPUT_EVENT_KEYPRESS      InputEventType = 1
	InputEventType_INPUT_EVENT_KEYRELEASE    InputEventType = 2
	InputEventType_INPUT_EVENT_KEYREPEAT     InputEventType = 3
	InputEventType_INPUT_EVENT_ABSPOSITION   InputEventType = 4
	InputEventType_INPUT_EVENT_RELPOSITION   InputEventType = 5
	InputEventType_INPUT_EVENT_TOUCHPRESS    InputEventType = 6
	InputEventType_INPUT_EVENT_TOUCHRELEASE  InputEventType = 7
	InputEventType_INPUT_EVENT_TOUCHPOSITION InputEventType = 8
)

var InputEventType_name = map[int32]string{
	0: "INPUT_EVENT_NONE",
	1: "INPUT_EVENT_KEYPRESS",
	2: "INPUT_EVENT_KEYRELEASE",
	3: "INPUT_EVENT_KEYREPEAT",
	4: "INPUT_EVENT_ABSPOSITION",
	5: "INPUT_EVENT_RELPOSITION",
	6: "INPUT_EVENT_TOUCHPRESS",
	7: "INPUT_EVENT_TOUCHRELEASE",
	8: "INPUT_EVENT_TOUCHPOSITION",
}
var InputEventType_value = map[string]int32{
	"INPUT_EVENT_NONE":          0,
	"INPUT_EVENT_KEYPRESS":      1,
	"INPUT_EVENT_KEYRELEASE":    2,
	"INPUT_EVENT_KEYREPEAT":     3,
	"INPUT_EVENT_ABSPOSITION":   4,
	"INPUT_EVENT_RELPOSITION":   5,
	"INPUT_EVENT_TOUCHPRESS":    6,
	"INPUT_EVENT_TOUCHRELEASE":  7,
	"INPUT_EVENT_TOUCHPOSITION": 8,
}

func (x InputEventType) String() string {
	return proto.EnumName(InputEventType_name, int32(x))
}
func (InputEventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EmptyRequest struct {
}

func (m *EmptyRequest) Reset()                    { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string            { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()               {}
func (*EmptyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EmptyReply struct {
}

func (m *EmptyReply) Reset()                    { *m = EmptyReply{} }
func (m *EmptyReply) String() string            { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()               {}
func (*EmptyReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Point struct {
	X float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Point) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type InputEvent struct {
	Ts         *google_protobuf.Duration `protobuf:"bytes,1,opt,name=ts" json:"ts,omitempty"`
	DeviceType InputDeviceType           `protobuf:"varint,2,opt,name=device_type,json=deviceType,enum=mutablelogic.InputDeviceType" json:"device_type,omitempty"`
	EventType  InputEventType            `protobuf:"varint,3,opt,name=event_type,json=eventType,enum=mutablelogic.InputEventType" json:"event_type,omitempty"`
	Scancode   uint32                    `protobuf:"varint,4,opt,name=scancode" json:"scancode,omitempty"`
	Position   *Point                    `protobuf:"bytes,5,opt,name=position" json:"position,omitempty"`
	Relative   *Point                    `protobuf:"bytes,6,opt,name=relative" json:"relative,omitempty"`
	Slot       uint32                    `protobuf:"varint,7,opt,name=slot" json:"slot,omitempty"`
}

func (m *InputEvent) Reset()                    { *m = InputEvent{} }
func (m *InputEvent) String() string            { return proto.CompactTextString(m) }
func (*InputEvent) ProtoMessage()               {}
func (*InputEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InputEvent) GetTs() *google_protobuf.Duration {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *InputEvent) GetDeviceType() InputDeviceType {
	if m != nil {
		return m.DeviceType
	}
	return InputDeviceType_INPUT_TYPE_NONE
}

func (m *InputEvent) GetEventType() InputEventType {
	if m != nil {
		return m.EventType
	}
	return InputEventType_INPUT_EVENT_NONE
}

func (m *InputEvent) GetScancode() uint32 {
	if m != nil {
		return m.Scancode
	}
	return 0
}

func (m *InputEvent) GetPosition() *Point {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *InputEvent) GetRelative() *Point {
	if m != nil {
		return m.Relative
	}
	return nil
}

func (m *InputEvent) GetSlot() uint32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "mutablelogic.EmptyRequest")
	proto.RegisterType((*EmptyReply)(nil), "mutablelogic.EmptyReply")
	proto.RegisterType((*Point)(nil), "mutablelogic.Point")
	proto.RegisterType((*InputEvent)(nil), "mutablelogic.InputEvent")
	proto.RegisterEnum("mutablelogic.InputDeviceType", InputDeviceType_name, InputDeviceType_value)
	proto.RegisterEnum("mutablelogic.InputEventType", InputEventType_name, InputEventType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Remotes service

type RemotesClient interface {
	// Receive remotes
	Receive(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (Remotes_ReceiveClient, error)
}

type remotesClient struct {
	cc *grpc.ClientConn
}

func NewRemotesClient(cc *grpc.ClientConn) RemotesClient {
	return &remotesClient{cc}
}

func (c *remotesClient) Receive(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (Remotes_ReceiveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Remotes_serviceDesc.Streams[0], c.cc, "/mutablelogic.Remotes/Receive", opts...)
	if err != nil {
		return nil, err
	}
	x := &remotesReceiveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Remotes_ReceiveClient interface {
	Recv() (*InputEvent, error)
	grpc.ClientStream
}

type remotesReceiveClient struct {
	grpc.ClientStream
}

func (x *remotesReceiveClient) Recv() (*InputEvent, error) {
	m := new(InputEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Remotes service

type RemotesServer interface {
	// Receive remotes
	Receive(*EmptyRequest, Remotes_ReceiveServer) error
}

func RegisterRemotesServer(s *grpc.Server, srv RemotesServer) {
	s.RegisterService(&_Remotes_serviceDesc, srv)
}

func _Remotes_Receive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RemotesServer).Receive(m, &remotesReceiveServer{stream})
}

type Remotes_ReceiveServer interface {
	Send(*InputEvent) error
	grpc.ServerStream
}

type remotesReceiveServer struct {
	grpc.ServerStream
}

func (x *remotesReceiveServer) Send(m *InputEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _Remotes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mutablelogic.Remotes",
	HandlerType: (*RemotesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Receive",
			Handler:       _Remotes_Receive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "remotes/remotes.proto",
}

func init() { proto.RegisterFile("remotes/remotes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xdd, 0x6e, 0xda, 0x4c,
	0x10, 0xfd, 0xec, 0xf0, 0x97, 0x09, 0x1f, 0xd9, 0x2e, 0xa1, 0x31, 0x34, 0xa9, 0x22, 0x7a, 0x93,
	0xe6, 0xc2, 0x54, 0xf4, 0xb2, 0x52, 0x25, 0x7e, 0x56, 0x2a, 0x85, 0x60, 0x6b, 0x6d, 0x2a, 0xd1,
	0x1b, 0xc4, 0xcf, 0x16, 0x59, 0x32, 0xac, 0x8b, 0x17, 0x14, 0xbf, 0x42, 0xdf, 0xa2, 0x2f, 0xd3,
	0xe7, 0xaa, 0xbc, 0xc6, 0x8e, 0x81, 0xb6, 0x57, 0x9e, 0xd9, 0x33, 0x67, 0xce, 0x99, 0x5d, 0x0f,
	0x54, 0x36, 0x6c, 0xc5, 0x05, 0xf3, 0x1b, 0xfb, 0xaf, 0xee, 0x6d, 0xb8, 0xe0, 0xb8, 0xb8, 0xda,
	0x8a, 0xe9, 0xcc, 0x65, 0x2e, 0x5f, 0x3a, 0xf3, 0xda, 0xeb, 0x25, 0xe7, 0x4b, 0x97, 0x35, 0x24,
	0x36, 0xdb, 0x7e, 0x6b, 0x2c, 0xb6, 0x9b, 0xa9, 0x70, 0xf8, 0x3a, 0xaa, 0xae, 0x97, 0xa0, 0x48,
	0x56, 0x9e, 0x08, 0x28, 0xfb, 0xbe, 0x65, 0xbe, 0xa8, 0x17, 0x01, 0xf6, 0xb9, 0xe7, 0x06, 0xf5,
	0x37, 0x90, 0x35, 0xb9, 0xb3, 0x16, 0xb8, 0x08, 0xca, 0x93, 0xa6, 0xdc, 0x29, 0xf7, 0x2a, 0x55,
	0x9e, 0xc2, 0x2c, 0xd0, 0xd4, 0x28, 0x0b, 0xea, 0xbf, 0x54, 0x80, 0xde, 0xda, 0xdb, 0x0a, 0xb2,
	0x63, 0x6b, 0x81, 0xdf, 0x82, 0x2a, 0x7c, 0x59, 0x7b, 0xd1, 0xac, 0xea, 0x91, 0xbc, 0x1e, 0xcb,
	0xeb, 0xdd, 0xbd, 0x3c, 0x55, 0x85, 0x8f, 0x3f, 0xc2, 0xc5, 0x82, 0xed, 0x9c, 0x39, 0x9b, 0x88,
	0xc0, 0x63, 0xb2, 0x63, 0xa9, 0x79, 0xab, 0xa7, 0x07, 0xd0, 0x65, 0xe7, 0xae, 0xac, 0xb2, 0x03,
	0x8f, 0x51, 0x58, 0x24, 0x31, 0xfe, 0x00, 0xc0, 0x42, 0xcd, 0x88, 0x7e, 0x26, 0xe9, 0x37, 0x7f,
	0xa0, 0x4b, 0x63, 0x92, 0x7d, 0xce, 0xe2, 0x10, 0xd7, 0xa0, 0xe0, 0xcf, 0xa7, 0xeb, 0x39, 0x5f,
	0x30, 0x2d, 0x73, 0xa7, 0xdc, 0xff, 0x4f, 0x93, 0x1c, 0x37, 0xa0, 0xe0, 0x71, 0xdf, 0x09, 0x8d,
	0x6a, 0x59, 0x39, 0x49, 0xf9, 0xb0, 0xad, 0xbc, 0x15, 0x9a, 0x14, 0x85, 0x84, 0x0d, 0x73, 0xa7,
	0xc2, 0xd9, 0x31, 0x2d, 0xf7, 0x0f, 0x42, 0x5c, 0x84, 0x31, 0x64, 0x7c, 0x97, 0x0b, 0x2d, 0x2f,
	0x95, 0x65, 0xfc, 0xf0, 0x53, 0x81, 0xcb, 0xa3, 0x71, 0x71, 0x19, 0x2e, 0x7b, 0x43, 0x73, 0x64,
	0x4f, 0xec, 0xb1, 0x49, 0x26, 0x43, 0x63, 0x48, 0xd0, 0x7f, 0xf8, 0x1a, 0xca, 0xa9, 0xc3, 0x3e,
	0x19, 0xb7, 0x8d, 0x16, 0xed, 0x22, 0x05, 0x5f, 0x01, 0x4a, 0x01, 0x8f, 0xc6, 0xc8, 0x22, 0x48,
	0xc5, 0x35, 0x78, 0x99, 0x3a, 0xb5, 0x8d, 0x51, 0xe7, 0x93, 0xd5, 0xa1, 0x84, 0x0c, 0x51, 0xe6,
	0xa8, 0xd5, 0x67, 0x63, 0x6c, 0xd9, 0xbd, 0x4e, 0x1f, 0x15, 0x70, 0x05, 0x5e, 0xa4, 0x00, 0x4a,
	0x1e, 0x0d, 0x9b, 0x20, 0xf4, 0xf0, 0x43, 0x85, 0xd2, 0xe1, 0x9d, 0x3e, 0x8b, 0x92, 0x2f, 0x64,
	0x68, 0xc7, 0x1e, 0x35, 0xb8, 0x4a, 0x9f, 0xf6, 0xc9, 0xd8, 0xa4, 0xc4, 0xb2, 0x90, 0xf2, 0x6c,
	0x27, 0x41, 0x28, 0x19, 0x90, 0x96, 0xb4, 0x5a, 0x85, 0xca, 0x09, 0x66, 0x92, 0x96, 0x8d, 0xce,
	0xf0, 0x2b, 0xb8, 0x4e, 0x43, 0xad, 0xb6, 0x65, 0x1a, 0x56, 0xcf, 0xee, 0x19, 0xe1, 0x18, 0x47,
	0x20, 0x25, 0x83, 0x04, 0xcc, 0x1e, 0x0b, 0xca, 0x0b, 0x88, 0xcc, 0xe4, 0xf0, 0x0d, 0x68, 0x27,
	0x58, 0x6c, 0x27, 0x8f, 0x6f, 0xa1, 0x7a, 0xca, 0x8c, 0x1b, 0x17, 0x9a, 0x03, 0xc8, 0xd3, 0x68,
	0xf7, 0x70, 0x2b, 0x0c, 0xe7, 0x2c, 0x7c, 0xda, 0xda, 0xe1, 0xcb, 0xa7, 0xd7, 0xab, 0xa6, 0xfd,
	0xed, 0xef, 0x7c, 0xa7, 0xb4, 0xcf, 0xbf, 0xe6, 0xf7, 0x9b, 0x3c, 0xcb, 0xc9, 0x7d, 0x79, 0xff,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xf0, 0x44, 0xee, 0xe3, 0x03, 0x00, 0x00,
}
